Altimeter node monitor
Pitt-RAS/iarc7_sensors pull request #23
Opened 2017-07-18 02:29 UTC by Liam-Berti

2017-07-18 03:12 UTC, asaba96 commented on src/altimeter.cpp
> +#include "iarc7_safety/SafetyClient.hpp"
Can you reorder your #includes, so put line 11 on line 6

2017-07-18 03:18 UTC, amiller27 requested changes

2017-07-18 03:18 UTC, amiller27 commented on src/altimeter.cpp
> +    ROS_ASSERT_MSG(safety_client.formBond(),
The bond shouldn't be formed until the node has finished all its startup procedures, i.e. it's connected to the lidarlite successfully.  Might also want to make sure the topics / transforms this depends on are sending messages, but not necessarily.

2017-07-19 03:07 UTC, amiller27 commented on src/altimeter.cpp
> +            ROS_ASSERT_MSG(safety_client.formBond(),
We shouldn't really call this more than once, this should be before the loop

2017-07-21 19:13 UTC, amiller27 approved these changes

2017-07-21 19:49 UTC, aftersomemath approved these changes

2017-07-21 19:49 UTC, merged